using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Ared.Core.AutoSheetData.Data;
using UnityEditor;

namespace Ared.Core.AutoSheetData.Editor
{
    internal static class CodeGenerator
    {
        internal class ColumnDef
        {
            public string HeaderRaw;
            public string FieldName;
            public EColumnType ColumnType;
        }

        internal static void EnsureFolder(string path)
        {
            if (AssetDatabase.IsValidFolder(path)) return;

            var parts = path.Split('/');
            var current = parts[0];
            for (int i = 1; i < parts.Length; i++)
            {
                var next = current + "/" + parts[i];
                if (!AssetDatabase.IsValidFolder(next))
                    AssetDatabase.CreateFolder(current, parts[i]);
                current = next;
            }
        }

        internal static (string rowClassName, string collectionClassName) ComputeTypeNames(string sheetName)
        {
            var baseName = SchemaUtils.SanitizeClassName(sheetName);
            return ($"{baseName}Row", $"{baseName}Collection");
        }

        internal static string BuildRowClassCode(string ns, string rowClassName, IReadOnlyList<ColumnDef> columns)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by AutoSheetData. Do not edit manually.");
            sb.AppendLine("using System;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine("    [Serializable]");
            sb.AppendLine($"    public class {rowClassName}");
            sb.AppendLine("    {");
            foreach (var col in columns)
                sb.AppendLine($"        public {SchemaUtils.ToCSharpType(col.ColumnType)} {col.FieldName}; // {col.HeaderRaw}");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        internal static string BuildCollectionClassCode(string ns, string collectionClassName, string rowClassName)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by AutoSheetData. Do not edit manually.");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using Ared.AutoSheetData.Data;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine($"    public class {collectionClassName} : DataCollection<{rowClassName}> {{ }}");
            sb.AppendLine("}");
            return sb.ToString();
        }

        internal static void WriteCodeFile(string folderPath, string fileName, string code)
        {
            EnsureFolder(folderPath);
            var fullPath = Path.Combine(folderPath, fileName);
            File.WriteAllText(fullPath, code, new UTF8Encoding(false));
        }

        internal static List<ColumnDef> BuildColumnsFromConfig(List<string> headers, List<EColumnType> types)
        {
            int count = Math.Max(headers?.Count ?? 0, types?.Count ?? 0);
            var rawNames = new List<string>();
            for (int i = 0; i < count; i++)
                rawNames.Add(i < (headers?.Count ?? 0) ? headers[i] : $"Col{i + 1}");

            var sanitized = SchemaUtils.MakeUnique(rawNames.Select(SchemaUtils.SanitizeFieldName));

            var cols = new List<ColumnDef>();
            for (int i = 0; i < count; i++)
            {
                cols.Add(new ColumnDef
                {
                    HeaderRaw = rawNames[i],
                    FieldName = sanitized[i],
                    ColumnType = i < (types?.Count ?? 0) ? types[i] : EColumnType.String
                });
            }
            return cols;
        }
    }
}